name: CD

on:
  push:
    branches: [ main ]

jobs:
  ci:
    name: 进行持续交付
    runs-on: ubuntu-latest
    steps:

      - name: 检出代码
        uses: actions/checkout@v2

      - name: 单元测试
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: 上传单元测试结果
        uses: codecov/codecov-action@v1.0.14
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      # 如果不修正时区，会导致后续交叉编译步骤中，注入程序的版本号中的时间不正确
      # https://blog.csdn.net/xo19882011/article/details/83789702
      - name: 修正构建环境的时区
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: 交叉编译
        # 不添加构建参数 CGO_ENABLED=0 会导致编译出的二进制程序无法在 alpine 中运行
        run: CGO_ENABLED=0 go build -ldflags "-X 'github.com/offcn-jl/gaea-back-end/commons/config.Version=${GITHUB_SHA:0:7} [ `date +"%Y/%m/%d %H:%M:%S"` ]'" -o gaea

      - name: 构建镜像
        run: |
          docker build -t "ccr.ccs.tencentyun.com/gaea/back-end:${GITHUB_SHA:0:7}" .
          docker tag "ccr.ccs.tencentyun.com/gaea/back-end:${GITHUB_SHA:0:7}" "ccr.ccs.tencentyun.com/gaea/back-end:latest"

      - name: 推送镜像
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_PASSWORD}} ccr.ccs.tencentyun.com
          docker push "ccr.ccs.tencentyun.com/gaea/back-end:${GITHUB_SHA:0:7}"
          docker push "ccr.ccs.tencentyun.com/gaea/back-end:latest"
